### ISSUE TITLE
Scrape stopped at 74%?

### ISSUE THREAD

**Issue by Owasgwi** [sdelgadoc/download-tweets-ai-text-gen-plus#8] opened 2020-12-20 11:06 UTC
I scraped a Tweeter, and it stopped at 74%, why is this?

The user's profile shows he has 1,641 tweets, and it stopped at 1,244.

![why1244](https://user-images.githubusercontent.com/51683127/102711666-4cf7a300-4270-11eb-8fa1-f0e3d07f5947.PNG)

**Comment by Owasgwi** [comment] 2020-12-20 16:21
I just scraped my own account, and it too stopped what looks to be pre-maturely, at 19%, but I think it is because the Tweet counter on the profile page includes all tweets from a user (replies, retweets, tweets), not just "original" tweets.

**Comment by sdelgadoc** [comment] 2020-12-20 17:15
Yes, you are correct.  The progress bar was counting the original tweets, and replies collected from the API, but not the retweets.

I think this is confusing for users, so I updated the code to count all tweets collected from the API.

Could you please clone the repo, and test the code to see if the issue is fixed on your side?  Thanks in advance for your help.

**Comment by Owasgwi** [comment] 2020-12-20 18:37
Here's the result:

![goodbutwhy1635](https://user-images.githubusercontent.com/51683127/102721386-4e948b80-42af-11eb-82ed-f02bc0c65d02.PNG)

**Comment by sdelgadoc** [comment] 2020-12-20 19:30
Thanks, this is very helpful.  However, the result is surprising.  Twitter says the user has posted 1,641 tweets but the API is only returning 1,635.

I tried to reproduce the issue in a couple of different ways with my own account, but wasn't able to.  In all cases I got the correct number of tweets.  Debugging will be tough due to the large volume of tweets, but I'll continue to keep my eye out for potential issues.

Until then, hopefully those 6 missing tweets aren't critical to training your bot, and you can use the data to start training the GPT model.

Let me know if you have any other questions or issues.

**Closed** 2020-12-21 01:00 UTC
